Example with build_proc option
pantographe/view_component-form pull request #142
Opened 2023-03-23 21:33 UTC by wooly

2023-05-01 20:28 UTC, Spone requested changes
We suggest a small naming change.

Also, can you implement the same changes in `CollectionRadioButtonsComponent`?

2023-05-01 20:28 UTC, Spone commented on app/components/view_component/form/collection_check_boxes_component.rb
> +        build_proc = options.delete(:build_proc)
```suggestion
        element_proc = options.delete(:element_proc)
```

2023-05-01 20:28 UTC, Spone commented on app/components/view_component/form/collection_check_boxes_component.rb
> +        ).render(&build_proc)
```suggestion
        ).render(&element_proc)
```

2023-05-01 20:28 UTC, Spone commented on spec/view_component/form/collection_check_boxes_component_spec.rb
> +        build_proc: proc do |b|
```suggestion
        element_proc: proc do |b|
```

2023-05-01 20:31 UTC, Spone commented
We'll take care of updating the README.

2023-05-04 05:58 UTC, wooly commented
> We suggest a small naming change.
> 
> Also, can you implement the same changes in `CollectionRadioButtonsComponent`?

Yep, can do that in a few hours :+1:

2023-05-04 08:31 UTC, wooly commented
@Spone how does that look?

2023-05-04 12:35 UTC, Spone commented
@wooly looking good! We'll update the README and merge.

2023-05-04 12:35 UTC, Spone approved these changes

2023-05-04 18:52 UTC, wooly commented
Many thanks!

2023-05-29 12:09 UTC, rubiii commented
Hey. We started using this library a couple of weeks ago and this feature would be greatly appreciated.
So thank you very much!

We would suggest a small change though. Currently, the `element_proc` is expected to be passed via
`options` and that's fine, as long as you don't have any `html_options`. Since both args are optional,
we fixed this on our side by just looking into both hashes:

```ruby
element_proc = options.delete(:element_proc) || html_options.delete(:element_proc)
```

What do you think?

2023-05-30 09:53 UTC, Spone commented
Good call @rubiii! Can you make the change @wooly please?

2023-05-31 19:19 UTC, rubiii commented
@wooly I could prepare a PR to your branch if that would help you out.
Given my proposed changed looks valid to you of course.

2023-05-31 21:06 UTC, wooly commented
@rubliii that would be super if you could do that as I'm currently on holiday! Thanks! I guess what we're saying then is that the element_proc can be passed in via both options and html_options? Should we then delete from both in the extremely unlikely case that it's specified in both?

2023-06-01 09:26 UTC, rubiii commented
Thanks for replying from your holidays @wooly :)

Good question. We could check and delete the option from both hashes and also raise an error to cover the probably unlikely case where both option hashes include an `element_proc`. That would be a little more code, but it's probably good to prevent any confusion.

2023-06-01 09:33 UTC, Spone commented
> That would be a little more code, but it's probably good to prevent any confusion.

Agreed!

2023-06-26 20:56 UTC, Spone commented
@rubiii @wooly let us know if you need help to wrap this up!

2023-06-27 07:06 UTC, wooly commented
Sorry for the delay. Have merged @rubiii's PR into my branch now, so we should be good to go.

2023-06-29 11:28 UTC, Spone commented
Hmm we have to fix the CI failures on `main` first :/

2023-08-08 02:29 UTC, wooly commented
@Spone anything I can do to get this over the line?

2023-08-08 21:01 UTC, Spone commented
Hi @wooly thanks for your time on this PR. The past few months have been pretty hectic at work and now I'm on holiday to recharge batteries 🙂

I think we still have to figure out why CI is failing on main before releasing a new version, but in the meantime I think we can go ahead and merge this, if you can update the changelog beforehand it would be perfect 🙏

2023-08-18 00:02 UTC, wooly commented
Thanks @Spone - have updated CHANGELOG.md

2023-08-18 00:13 UTC, merged