Fix: Rename text_area helper to textarea for Rails 8 compatibility
pantographe/view_component-form pull request #181
Opened 2024-11-27 03:47 UTC by aki77

This PR addresses the issue where the `text_area` helper is no longer functional in Rails 8 due to its renaming to `textarea`.

https://github.com/rails/rails/pull/52467

2024-11-28 09:13 UTC, Spone commented
Hi @aki77 thanks for contributing! Can you please add some tests to your PR?

2025-01-31 16:34 UTC, nicolas-brousse requested changes
Thanks @aki77 

I did a review and add a comment.
May you also do the following ?

- Rename `text_area` by `textarea` in the README
- Adding a line in the Changelog
- Do the same changes for `rich_text_area`

If you need I may take time to finalize the changes.

2025-01-31 16:34 UTC, nicolas-brousse commented on lib/view_component/form/helpers/rails.rb
> +              textarea
I think we may keep it at auto generate like it was. Like for `phone_field` and `telephone_field`.

And so removing the `textarea` method bellow, and moving the alias just after `alias_method :phone_field, :telephone_field`.

2025-03-06 21:43 UTC, nicolas-brousse approved these changes

2025-03-15 15:19 UTC, nicolas-brousse commented
@Spone I did some test on a Rails 6.1 app and a Rails 8 app. Textarea shows up without issues.

Feel free to review this when you've got some time for :blush:

2025-03-15 20:55 UTC, Spone requested changes

2025-03-15 20:55 UTC, Spone commented on README.md
> +**Supported:** `button` `check_box` `collection_check_boxes` `collection_radio_buttons` `collection_select` `color_field` `date_field` `date_select` `datetime_field` `datetime_local_field` `datetime_
```suggestion
**Supported:** `button` `check_box` `collection_check_boxes` `collection_radio_buttons` `collection_select` `color_field` `date_field` `date_select` `datetime_field` `datetime_local_field` `datetime_select` `email_field` `fields` `fields_for` `file_field` `field_id` `grouped_collection_select` `hidden_field` `month_field` `number_field` `password_field` `phone_field` `radio_button` `range_field` `search_field` `select` `submit` `telephone_field` `textarea` (formerly `text_area` before Rails 8) `text_field` `time_field` `time_select` `time_zone_select` `to_model` `to_partial_path` `url_field` `week_field` `weekday_select`
```

2025-03-15 20:55 UTC, Spone commented on README.md
> +**Partially supported:** `label` (blocks not supported) `rich_textarea` (untested)
```suggestion
**Partially supported:** `label` (blocks not supported) `rich_textarea` (formerly`rich_text_area` before Rails 8) (untested)
```

2025-03-15 20:58 UTC, Spone approved these changes

2025-03-16 11:26 UTC, merged

2025-04-03 14:26 UTC, nicolas-brousse commented
Hi @henrikbjorn. Thanks for your feedback, there is a PR opened to fix this #189.

2025-04-04 06:49 UTC, henrikbjorn commented
@nicolas-brousse depending on when the PR can be merged, can this be reverted?

2025-04-04 14:24 UTC, henrikbjorn commented
> @henrikbjorn as said in #189, we've yanked the `0.2.10` release. And the PR may be merged soon. As soon as it's merged, I'll do a new release.

Thank you :)

Would say that just re-releasing 0.2.9 as 0.2.11 would be a better approach.