Add custom eq_html RSpec matcher
pantographe/view_component-form pull request #32
Opened 2021-07-06 21:59 UTC by Spone

Close #27

2021-07-08 17:57 UTC, nicolas-brousse commented
@Spone I permit myself to refactor a bit the matcher. What do you think about?

2021-07-08 19:29 UTC, Spone commented
I prefer the output of my version:

![image](https://user-images.githubusercontent.com/38524/124979555-7bce3e80-e033-11eb-8426-19308dd9d4ba.png)

It's more readable and easier to find the error with the diff, if you compare to your version:

![image](https://user-images.githubusercontent.com/38524/124979602-87ba0080-e033-11eb-96ba-66f72fc0c69b.png)

2021-07-08 19:32 UTC, Spone commented
But I like this change:

```diff
- expect(component.to_html).to eq_html <<~HTML
+ expect(component).to eq_html <<~HTML
```

2021-09-09 19:19 UTC, nicolas-brousse requested changes
Verify there is no new specs that must include this new matcher

2021-09-09 19:19 UTC, nicolas-brousse commented on spec/support/matchers/eq_html.rb
> +      @actual.include?(expected_formatted)
```suggestion
      @actual == expected_formatted
```

2021-09-09 19:19 UTC, nicolas-brousse commented on spec/support/matchers/eq_html.rb
> +      "expected that HTML fragment contain #{expected_formatted}"
Take previous failure message back

2021-09-09 22:28 UTC, nicolas-brousse approved these changes

2021-09-09 22:31 UTC, merged