Per component Builder customization
pantographe/view_component-form pull request #54
Opened 2021-09-11 12:48 UTC by nicolas-brousse

Closes #48

2021-09-11 12:48 UTC, nicolas-brousse commented
@hans I did a wip for the issue :)

2021-09-11 16:24 UTC, nicolas-brousse commented on lib/view_component/form/builder.rb
> +        def add_namespace(namespace)
@Spone maybe just `namespace`

2021-09-13 14:38 UTC, Spone requested changes

2021-09-16 19:26 UTC, Spone commented on lib/view_component/form/builder.rb
> +        end
```suggestion
        def namespace(namespace)
          raise NamespaceAlreadyAddedError, "This component namespace is already added" if components_namespaces.include? namespace
        
          components_namespaces.prepend namespace
        end
```

2021-09-16 19:45 UTC, Spone approved these changes

2021-09-16 19:53 UTC, merged